#!/bin/bash

# TeletonicMD VPS Deployment Script
# This script helps deploy OpenEMR changes to your VPS

echo "================================================"
echo "TeletonicMD OpenEMR VPS Deployment Helper"
echo "================================================"
echo ""
echo "This script will help you deploy changes to your VPS at 157.173.212.240"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "Please run these commands on your VPS:"
echo ""
echo -e "${YELLOW}Step 1: SSH into your VPS${NC}"
echo "ssh root@157.173.212.240"
echo ""

echo -e "${YELLOW}Step 2: Navigate to OpenEMR directory${NC}"
echo "cd /var/www/html/openemr"
echo "(or wherever your OpenEMR is installed)"
echo ""

echo -e "${YELLOW}Step 3: Check current branch and status${NC}"
echo "git branch"
echo "git status"
echo ""

echo -e "${YELLOW}Step 4: Pull latest changes from GitHub${NC}"
echo "git fetch origin"
echo "git pull origin master"
echo ""

echo -e "${YELLOW}Step 5: Verify the custom files exist${NC}"
echo "ls -la templates/login/layouts/teletonicmd_custom.html.twig"
echo "ls -la interface/themes/teletonic_custom/main.css"
echo ""

echo -e "${YELLOW}Step 6: Check OpenEMR configuration${NC}"
echo "grep -n 'login_page_layout' library/globals.inc.php | head -5"
echo "grep -n 'login_tagline_text' library/globals.inc.php | head -5"
echo ""

echo -e "${YELLOW}Step 7: Clear any caches${NC}"
echo "# Clear PHP opcache if using it"
echo "systemctl restart php7.4-fpm"
echo "# or"
echo "systemctl restart php8.0-fpm"
echo ""
echo "# Restart Apache"
echo "systemctl restart apache2"
echo "# or if using Nginx"
echo "systemctl restart nginx"
echo ""

echo -e "${YELLOW}Step 8: Check permissions${NC}"
echo "chown -R www-data:www-data /var/www/html/openemr"
echo "chmod -R 755 /var/www/html/openemr"
echo ""

echo -e "${YELLOW}Step 9: Check error logs for issues${NC}"
echo "tail -f /var/log/apache2/error.log"
echo "# or"
echo "tail -f /var/log/nginx/error.log"
echo ""

echo "================================================"
echo "Troubleshooting Checklist:"
echo "================================================"
echo ""
echo "1. [ ] Is the VPS pulling from the correct GitHub repository?"
echo "   Run: git remote -v"
echo ""
echo "2. [ ] Is the VPS on the master branch?"
echo "   Run: git branch"
echo ""
echo "3. [ ] Are the custom files present on the VPS?"
echo "   Run: ls -la templates/login/layouts/*.twig"
echo ""
echo "4. [ ] Is the login_page_layout set to teletonicmd_custom?"
echo "   Run: grep teletonicmd_custom library/globals.inc.php"
echo ""
echo "5. [ ] Are there any PHP errors?"
echo "   Check: /var/log/apache2/error.log"
echo ""
echo "6. [ ] Is the CSS file accessible?"
echo "   Try: curl http://localhost/openemr/interface/themes/teletonic_custom/main.css"
echo ""

echo "================================================"
echo "If changes still don't appear, try:"
echo "================================================"
echo ""
echo -e "${GREEN}Option 1: Force reset to GitHub version${NC}"
echo "git fetch origin"
echo "git reset --hard origin/master"
echo ""
echo -e "${GREEN}Option 2: Check if database needs updating${NC}"
echo "mysql -u root -p openemr -e \"SELECT gl_value FROM globals WHERE gl_name='login_page_layout';\""
echo ""
echo -e "${GREEN}Option 3: Manual database update${NC}"
echo "mysql -u root -p openemr -e \"UPDATE globals SET gl_value='login/layouts/teletonicmd_custom.html.twig' WHERE gl_name='login_page_layout';\""
echo ""
echo -e "${GREEN}Option 4: Check OpenEMR admin settings${NC}"
echo "1. Login to OpenEMR admin"
echo "2. Go to Administration > Globals > Login Page"
echo "3. Look for 'Login Page Layout'"
echo "4. Select 'TeletonicMD Custom - Modern Medical Interface'"
echo "5. Save changes"
echo ""

echo "================================================"
echo "Expected Results After Deployment:"
echo "================================================"
echo "✅ Login page shows: 'Welcome to TeleTonicMD Secure Telemedicine Portal'"
echo "✅ Pastel blue and lavender color scheme"
echo "✅ Modern, professional medical interface"
echo "✅ Responsive design with smooth animations"
echo ""