name: Deploy to VPS

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 157.173.212.240
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/html
          git pull origin master
          # Clear any caches if needed
          # systemctl restart apache2
          echo "Deployment completed successfully"